dist: xenial
sudo: false
language: python
python:
  - '2.7'
  - '3.6'
  - '3.7'
install:
  - pip install -r requirements-test.txt
script:
  - tox
deploy:
  - provider: pypi
    user: "__token__"
    password:
      secure: WfO1K0WQwsCSytOZLmobEyfGrGuw9qKgMCvn3c3Wnm6Oiby/A6Amoglfb++969AmSc4sipTZR7mgwb5ugIuWjDBfbupSGQFZt9rAAzL6eTJeDQvSjhyI4ipjSWIBi05T31OpTc/z3mWEBWf0EsiuXc+Bxm4yQdKUd/GPc5UWgOcytWEu5we8JhJQdln9DuRB4nqO0ET0ZxVIeogLLgfZMLTPnuppQzEFYI8gszNm2bRDjRednN5bNhAeX60ndWjgl2kOZwZ0zFIIJYgfZ2XXnH25/s6YkDX5ADU3YGp0oPZO4iWghKLX51zB88aOvuqcAWFB0vGJnMFjFbqweHGq+bpVL0jRAKNMhUX8E3cZ1wXAIdVvl33RlXHXqTcVus/fZPIlFRw2wNLrUDAOGgAR/r/RD4xikxGPNYZNMFjGTVf9zeefD/6OODd1bU1v7FhuFlDHJsfMyiVCEePbbKY/rfsawT+JdyuM8FvJhgYztUF8BeRs7i7RPys2uFNZFxh3gmQL30TqM2dcNJNaOtr+LpXL5Ek0A4ieoAGVSjsUfTtkrdfXlqMKwQiVL7UsT1QH2Txh1LXNaADMxuMX6dXl8QavqukP7+iG69OtcHgyo+OhKGHg1j8HdGAa1HuVFVo8v+aiorR+SidjDuIMAkyXfhz3j5774GxtKq++jVjcCxA=
    on:
      tags: true
      python: '3.6'
