name: release

on:
  push:
    tags:
      - obsah-[0-9]+.[0-9]+.[0-9]+

jobs:
  release:

    runs-on: ubuntu-latest

    permissions:
      id-token: write

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install wheel and setuptools
        run: pip install wheel setuptools
      - name: Build sdist and wheel
        run: python setup.py sdist bdist_wheel
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@v1.12.3
